Repository NextGenDevOrg/03-JavaScript-Learning, pull requests merged in 2021-12, with the labels that each got.

#13 initial-commit
  tasks-by-users/anask601/05-movies-by-filter/assets/scripts/main.js
  tasks-by-users/anask601/05-movies-by-filter/assets/styles/app.css
  tasks-by-users/anask601/05-movies-by-filter/index.html
Labels: enhancement

#12 intial-commit
  tasks-by-users/anask601/04-my-favorite-movie/assets/scripts/script.js
  tasks-by-users/anask601/04-my-favorite-movie/assets/styles/style.css
  tasks-by-users/anask601/04-my-favorite-movie/index.html
Labels: enhancement

#15 The Unconventional Calculator
  tasks-by-users/Abbas4tech/01- Unconventional Calculator/index.html
  tasks-by-users/Abbas4tech/01- Unconventional Calculator/style.css
Labels: documentation

#14 Added Monster killer game
  tasks-by-users/shaikh-7abish/01-monster-killer-game/assets/scripts/app.js
  tasks-by-users/shaikh-7abish/01-monster-killer-game/assets/scripts/extra.js
  tasks-by-users/shaikh-7abish/01-monster-killer-game/assets/styles/app.css
  tasks-by-users/shaikh-7abish/01-monster-killer-game/index.html
Labels: documentation

#17 added markup and styling
  tasks-by-users/Abbas4tech/01- Unconventional Calculator/app.js
  tasks-by-users/Abbas4tech/01- Unconventional Calculator/index.html
  tasks-by-users/Abbas4tech/01- Unconventional Calculator/style.css
Labels: documentation

#19 added calculator
  tasks-by-users/shaikh-7abish/02-basic-calculator/assets/calculator-removebg-preview.png
  tasks-by-users/shaikh-7abish/02-basic-calculator/assets/scripts/app.js
  tasks-by-users/shaikh-7abish/02-basic-calculator/assets/scripts/vendor.js
  tasks-by-users/shaikh-7abish/02-basic-calculator/assets/styles/app.css
  tasks-by-users/shaikh-7abish/02-basic-calculator/index.html
Labels: documentation

#16 01 js unconventional calculator using function
  tasks-by-users/mmusk/01-js-unconventional-calculator-fun/index.html
  tasks-by-users/mmusk/01-js-unconventional-calculator-fun/style.css
  tasks-by-users/mmusk/01-unconventional-calc/assets/assets/app.css
  tasks-by-users/mmusk/01-unconventional-calc/assets/assets/app.js
  tasks-by-users/mmusk/01-unconventional-calc/assets/assets/vendor.js
  tasks-by-users/mmusk/01-unconventional-calc/index.html
  tasks-by-users/mmusk/Readme.md
Labels: documentation

#20 created: unconventional calculator
  tasks-by-users/mmusk/01-unconventional-calc/assets/assets/app.css
Labels: documentation

#21 added-monster-killer-game
  tasks-by-users/Abbas4tech/02-monster-killrer-game/app.js
  tasks-by-users/Abbas4tech/02-monster-killrer-game/index.html
  tasks-by-users/Abbas4tech/02-monster-killrer-game/style.css
Labels: good first issue
